### ISSUE TITLE
Schema validation fails for schema version 2

### ISSUE THREAD

**Issue by vbreuss** [stryker-mutator/mutation-testing-elements#2493]
**Describe the bug**
I can't use the dashboard reporter to upload reports since the tool was updated to `3.8.1`.
The same report with tool version `3.7.1` is working.

**Logs**
I get the following error in the [Github Build Pipeline](https://github.com/Testably/Testably.Architecture.Rules/actions/runs/4900499091/jobs/8751189918):
```
All mutants have been tested, and your mutation score has been calculated
…[07:56:25 ERR] Failed to upload report to the dashboard at https://dashboard.stryker-mutator.io/api/reports/github.com/Testably/Testably.Architecture.Rules/main?module=Testably.Architecture.Rules
System.Net.Http.HttpRequestException: Response status code does not indicate success: [40](https://github.com/Testably/Testably.Architecture.Rules/actions/runs/4900499091/jobs/8751189918#step:5:41)0 (Bad Request).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Stryker.Core.Clients.DashboardClient.PublishReport(JsonReport report, String version)
[07:56:25 ERR] Uploading to stryker dashboard failed...`
```
When I revert back to v3.7.1 (`dotnet tool install dotnet-stryker --tool-path ../tools --version 3.7.1`) the report gets successfully uploaded:
```
All mutants have been tested, and your mutation score has been calculated
…Hint: by passing "--open-report:dashboard or -o:dashboard" the report will open 
automatically once Stryker is done.

Your report has been uploaded at:
https://dashboard.stryker-mutator.io/reports/github.com/Testably/Testably.Archit
ecture.Rules/topic/vb/change-stryker-version?module=Testably.Architecture.Rules
You can open it in your browser of choice.
```

**Expected behavior**
The report should be uploaded to https://dashboard.stryker-mutator.io/.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Type of project: core
 - Framework Version net6.0
 - Stryker Version 3.8.1

**Additional context**
In my other project Stryker also no longer uploads the dashboard report, but it [shows a different error message](https://github.com/Testably/Testably.Abstractions/actions/runs/4902459842/jobs/8754314766):
```
[16:04:59 INF] Initial testrun started.
[16:05:15 INF] Time Elapsed 00:01:13.8443548
Unhandled exception. System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Stryker.Core.Initialisation.ProjectMutator.EnrichTestProjectsWithTestInfo(InitialTestRun initialTestRun, TestProjectsInfo testProjectsInfo)
   at Stryker.Core.Initialisation.ProjectMutator.MutateProject(StrykerOptions options, IReporter reporters, IEnumerable`1 solutionProjects)
   at Stryker.Core.Initialisation.ProjectOrchestrator.MutateProjects(StrykerOptions options, IReporter reporters)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Stryker.Core.StrykerRunner.RunMutationTest(IStrykerInputs inputs, ILoggerFactory loggerFactory, IProjectOrchestrator projectOrchestrator)
   at Stryker.CLI.StrykerCli.RunStryker(IStrykerInputs inputs) in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 93
   at Stryker.CLI.StrykerCli.<>c__DisplayClass10_0.<Run>b__0() in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 68
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass143_0.<OnExecute>b__0(CancellationToken _)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Stryker.CLI.StrykerCli.Run(String[] args) in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 74
   at Stryker.CLI.Program.Main(String[] args) in /_/src/Stryker.CLI/Stryker.CLI/Program.cs:line 14
/home/runner/work/_temp/e6b4cac3-c1[27](https://github.com/Testably/Testably.Abstractions/actions/runs/4902459842/jobs/8754314766#step:5:28)-4f6d-b5f5-cf92c89680a7.sh: line 2:  1858 Aborted                 (core dumped) ../../tools/dotnet-stryker -f ../.github/stryker/Stryker.Config.Testing.json -v "${GITHUB_REF#refs/heads/}" -r "Dashboard" -r "cleartext"
Error: Process completed with exit code 1[34](https://github.com/Testably/Testably.Abstractions/actions/runs/4902459842/jobs/8754314766#step:5:35).
```

**Comment by rouke-broersma** [comment]
The html elements schema version enforces version 1, but we have had a breaking change and are on version 2.

https://github.com/stryker-mutator/mutation-testing-elements/blob/master/packages/report-schema/src/mutation-testing-report-schema.json#L15
